### ISSUE TITLE
utils.py模块无法导入 path_to_image

### ISSUE THREAD

**Issue by dflhuang111** [ZHO-ZHO-ZHO/ComfyUI-BiRefNet-ZHO#16]
提示ComfyUI/comfy/utils.py模块无法导入 path_to_image，查了文件确实也没有，comfyui已更新到最新
Traceback (most recent call last):
  File "/mnt/workspace/ComfyUI/nodes.py", line 1890, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-BiRefNet-ZHO/__init__.py", line 1, in <module>
    from . import birefnet
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-BiRefNet-ZHO/birefnet.py", line 7, in <module>
    from models.baseline import BiRefNet
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-BiRefNet-ZHO/models/baseline.py", line 16, in <module>
    from models.refinement.refiner import Refiner, RefinerPVTInChannels4, RefUNet
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-BiRefNet-ZHO/models/refinement/refiner.py", line 11, in <module>
    from dataset import class_labels_TR_sorted
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-BiRefNet-ZHO/dataset.py", line 10, in <module>
    from utils import path_to_image
ImportError: cannot import name 'path_to_image' from 'utils' (/mnt/workspace/ComfyUI/comfy/utils.py)

**Comment by royaiagent** [comment]
这个问题你解决了吗？

**Comment by laitianwen** [comment]
兄弟，这个问题解决了吗？

**Comment by the9an** [comment]
Changing `from utils` to `from .utils` tells Python that utils is a module in the current package or directory.

This change helps avoid conflicts with any other module named utils that might be installed globally or in other parts of your project.
https://github.com/ZHO-ZHO-ZHO/ComfyUI-BiRefNet-ZHO/blob/5d18c12b064b6cff014f7d8f8ef331006e07d9c6/dataset.py#L10

**Comment by zgglj2** [comment]
估计是和另外哪里的utils模块冲突了，把utils.py复制一份为myutils.py，然后把dataset.py中的from utils import path_to_image改为from myutils import path_to_image，就不会报错了

**Comment by erinsrc** [comment]
zgglj2 所说的方法可行，冲突解决了
