### ISSUE TITLE
更新到最新的Comfy-UI后出现下面报错，无法import

### ISSUE THREAD

**Issue by Philmar1986** [ZHO-ZHO-ZHO/ComfyUI-BiRefNet-ZHO#19]
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "", line 940, in exec_module
  File "", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\__init__.py", line 1, in 
    from . import birefnet
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\birefnet.py", line 7, in 
    from models.baseline import BiRefNet
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\models\baseline.py", line 16, in 
    from models.refinement.refiner import Refiner, RefinerPVTInChannels4, RefUNet
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\models\refinement\refiner.py", line 11, in 
    from dataset import class_labels_TR_sorted
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\dataset.py", line 10, in 
    from utils import path_to_image
ImportError: cannot import name 'path_to_image' from 'utils' (F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\utils\__init__.py)

Cannot import F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO module for custom nodes: cannot import name 'path_to_image' from 'utils' (F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\utils\__init__.py)

**Comment by q2we** [comment]
Traceback (most recent call last):                                                                                            
  File "D:\ComfyUI_cu121\ComfyUI\nodes.py", line 1993, in load_custom_node                                                    
    module_spec.loader.exec_module(module)                                                                                    
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module                                                     
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                
  File "D:\ComfyUI_cu121\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\__init__.py", line 1, in <module>                          
    from . import birefnet                                                                                                    
  File "D:\ComfyUI_cu121\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\birefnet.py", line 7, in <module>                          
    from models.baseline import BiRefNet                                                                                      
  File "D:\ComfyUI_cu121\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\models\baseline.py", line 16, in <module>                  
    from models.refinement.refiner import Refiner, RefinerPVTInChannels4, RefUNet                                             
  File "D:\ComfyUI_cu121\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\models\refinement\refiner.py", line 11, in <module>        
    from dataset import class_labels_TR_sorted                                                                                
  File "D:\ComfyUI_cu121\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\dataset.py", line 10, in <module>                          
    from utils import path_to_image                                                                                           
ImportError: cannot import name 'path_to_image' from 'utils' (D:\ComfyUI_cu121\ComfyUI\utils\__init__.py)

**Comment by AndyLeAI** [comment]
rollback previous version of comfyui maybe fix this issue !

**Comment by Jojo-xqt** [comment]
https://github.com/ZHO-ZHO-ZHO/ComfyUI-BiRefNet-ZHO/issues/16#issuecomment-2340643914
