### ISSUE TITLE
Unable to load, prompt:  from utils import check_download_model ImportError: cannot import name 'check_download_model' from 'utils' (D:\ComfyUI\utils\__init__.py)

### ISSUE THREAD

**Issue by cjc999** [ZHO-ZHO-ZHO/ComfyUI-BiRefNet-ZHO#21]
Unable to load, prompt:
 from utils import check_download_model
ImportError: cannot import name 'check_download_model' from 'utils' (D:\ComfyUI\utils\__init__.py)

**Comment by AugmentedRealityCat** [comment]
Same problem. Here is the log I got: 

```
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\__init__.py", line 1, in <module>
    from . import birefnet
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\birefnet.py", line 7, in <module>
    from models.baseline import BiRefNet
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\models\baseline.py", line 11, in <module>
    from models.backbones.build_backbone import build_backbone
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\models\backbones\build_backbone.py", line 8, in <module>
    from utils import check_download_model
ImportError: cannot import name 'check_download_model' from 'utils' (D:\ComfyUI_windows_portable\ComfyUI\utils\__init__.py)

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO module for custom nodes: cannot import name 'check_download_model' from 'utils' (D:\ComfyUI_windows_portable\ComfyUI\utils\__init__.py)
```

**Comment by MrBin-Vietnhat** [comment]
solve like this:
..\...\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\update
run Update_comfyui
![image](https://github.com/user-attachments/assets/509bf39b-5e20-4612-a4af-036c1b068fef)

**Comment by hillleaf** [comment]
Traceback (most recent call last):
  File "E:\sd-webui-aki\ComfyUI-aki-v1.2\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO\__init__.py", line 1, in <module>
    from . import birefnet
  File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO\birefnet.py", line 7, in <module>
    from models.baseline import BiRefNet
  File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO\models\baseline.py", line 16, in <module>
    from models.refinement.refiner import Refiner, RefinerPVTInChannels4, RefUNet
  File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO\models\refinement\refiner.py", line 11, in <module>
    from dataset import class_labels_TR_sorted
  File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO\dataset.py", line 10, in <module>
    from utils import path_to_image
ImportError: cannot import name 'path_to_image' from 'utils' (E:\sd-webui-aki\ComfyUI-aki-v1.2\utils\__init__.py)

**Comment by MrBin-Vietnhat** [comment]
> Traceback (most recent call last): File "E:\sd-webui-aki\ComfyUI-aki-v1.2\nodes.py", line 1993, in load_custom_node module_spec.loader.exec_module(module) File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO__init__.py", line 1, in from . import birefnet File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO\birefnet.py", line 7, in from models.baseline import BiRefNet File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO\models\baseline.py", line 16, in from models.refinement.refiner import Refiner, RefinerPVTInChannels4, RefUNet File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO\models\refinement\refiner.py", line 11, in from dataset import class_labels_TR_sorted File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO\dataset.py", line 10, in from utils import path_to_image ImportError: cannot import name 'path_to_image' from 'utils' (E:\sd-webui-aki\ComfyUI-aki-v1.2\utils__init__.py)

![image](https://github.com/user-attachments/assets/370f2f25-fc21-454e-8b6c-551f962a6133)

**Comment by lldacing** [comment]
可以用ComfyUI_BiRefNet_ll插件，新老模型都支持

**Comment by liutianping** [comment]
> > Traceback (most recent call last): File "E:\sd-webui-aki\ComfyUI-aki-v1.2\nodes.py", line 1993, in load_custom_node module_spec.loader.exec_module(module) File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO__init__.py", line 1, in from . import birefnet File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO\birefnet.py", line 7, in from models.baseline import BiRefNet File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO\models\baseline.py", line 16, in from models.refinement.refiner import Refiner, RefinerPVTInChannels4, RefUNet File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO\models\refinement\refiner.py", line 11, in from dataset import class_labels_TR_sorted File "E:\sd-webui-aki\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-BiRefNet-ZHO\dataset.py", line 10, in from utils import path_to_image ImportError: cannot import name 'path_to_image' from 'utils' (E:\sd-webui-aki\ComfyUI-aki-v1.2\utils__init__.py)
> 
> ![image](https://private-user-images.githubusercontent.com/181212595/366473556-370f2f25-fc21-454e-8b6c-551f962a6133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjc4OTUsIm5iZiI6MTcyODIyNzU5NSwicGF0aCI6Ii8xODEyMTI1OTUvMzY2NDczNTU2LTM3MGYyZjI1LWZjMjEtNDU0ZS04YjZjLTU1MWY5NjJhNjEzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxNTEzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTg0YzgzNWQ2NTcxYzJhYWI2MjliZjdlMjk0NTc3Mzg1ZGYxNGFmNDU3NjBhYzkzN2M2ZDdkYzAyYjcyNDQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RsGAvVLOenJBeuCPB3KJv8BE0MC8ucN8qLzI9Oe1oDE)

utils.py改为myutils.py，然后dataset.py第10行将utils改为myutils，完美解决。
