### ISSUE TITLE
Cannot import F:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-BiRefNet-ZHO module for custom nodes: cannot import name 'path_to_image' from 'utils' (F:\ComfyUI-aki-v1.1\utils\__init__.py)

### ISSUE THREAD

**Issue by xlibfly** [ZHO-ZHO-ZHO/ComfyUI-BiRefNet-ZHO#23]
Traceback (most recent call last):
  File "F:\ComfyUI-aki-v1.1\nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-BiRefNet-ZHO\__init__.py", line 1, in <module>
    from . import birefnet
  File "F:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-BiRefNet-ZHO\birefnet.py", line 7, in <module>
    from models.baseline import BiRefNet
  File "F:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-BiRefNet-ZHO\models\baseline.py", line 16, in <module>
    from models.refinement.refiner import Refiner, RefinerPVTInChannels4, RefUNet
  File "F:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-BiRefNet-ZHO\models\refinement\refiner.py", line 11, in <module>
    from dataset import class_labels_TR_sorted
  File "F:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-BiRefNet-ZHO\dataset.py", line 10, in <module>
    from utils import path_to_image
ImportError: cannot import name 'path_to_image' from 'utils' (F:\ComfyUI-aki-v1.1\utils\__init__.py)

Cannot import F:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI-BiRefNet-ZHO module for custom nodes: cannot import name 'path_to_image' from 'utils' (F:\ComfyUI-aki-v1.1\utils\__init__.py)
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.

**Comment by GammelSami** [comment]
#22 fixes it

**Comment by williamfang** [comment]
同问

**Comment by K-O-N-B** [comment]
还是这样：
Cannot import H:\ComfyUI-qiuye\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO module for custom nodes: cannot import name 'path_to_image' from 'utils' (H:\ComfyUI-qiuye\ComfyUI\utils\__init__.py)

**Comment by louis-she** [comment]
#26 修正了这个问题，也可以直接用我的 fork

`git clone https://github.com/louis-she/ComfyUI-BiRefNet-ZHO`

**Comment by K-O-N-B** [comment]
> #26 修正了这个问题，也可以直接用我的 fork
> 
> `git clone https://github.com/louis-she/ComfyUI-BiRefNet-ZHO`

需要删除原来的节点吗？还是直接安装就ok?

**Comment by louis-she** [comment]
删除原来的节点，再 git clone 我那个，然后重启 comfyui。

我的改动在 #26 里，都能看到

**Comment by Mediali-233** [comment]
> #26 修正了这个问题，也可以直接用我的 fork
> 
> `git clone https://github.com/louis-she/ComfyUI-BiRefNet-ZHO`

Traceback (most recent call last):
  File "D:\AI\ComfyUI-aki-v1.3\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BiRefNet-ZHO\__init__.py", line 1, in <module>
    from . import birefnet
  File "D:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BiRefNet-ZHO\birefnet.py", line 7, in <module>
    from .models.baseline import BiRefNet
  File "D:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BiRefNet-ZHO\models\baseline.py", line 11, in <module>
    from .backbones.build_backbone import build_backbone
  File "D:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BiRefNet-ZHO\models\backbones\build_backbone.py", line 5, in <module>
    from .pvt_v2 import pvt_v2_b2, pvt_v2_b5
  File "D:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BiRefNet-ZHO\models\backbones\pvt_v2.py", line 12, in <module>
    config = Config()
TypeError: Config.__init__() missing 1 required positional argument: 'stream_or_path'

**Comment by zjjderek** [comment]
> #26 修正了这个问题，也可以直接用我的 fork
> 
> `git clone https://github.com/louis-she/ComfyUI-BiRefNet-ZHO`

Traceback (most recent call last):
  File "I:\ComfyUI\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\__init__.py", line 1, in <module>
    from . import birefnet
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\birefnet.py", line 7, in <module>
    from .models.baseline import BiRefNet
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\models\baseline.py", line 11, in <module>
    from .backbones.build_backbone import build_backbone
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\models\backbones\build_backbone.py", line 5, in <module>
    from .pvt_v2 import pvt_v2_b2, pvt_v2_b5
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\models\backbones\pvt_v2.py", line 10, in <module>
    from config import Config
ModuleNotFoundError: No module named 'config'

**Comment by tiftiabc1234** [comment]
EDIT ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\dataset.py

find `from utils import path_to_image` and replace with
```

import logging
import os
import torch
from torchvision import transforms
import numpy as np
import random
import cv2
from PIL import Image


def path_to_image(path, size=(1024, 1024), color_type=['rgb', 'gray'][0]):
    if color_type.lower() == 'rgb':
        image = cv2.imread(path)
    elif color_type.lower() == 'gray':
        image = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    else:
        print('Select the color_type to return, either to RGB or gray image.')
        return
    if size:
        image = cv2.resize(image, size, interpolation=cv2.INTER_LINEAR)
    if color_type.lower() == 'rgb':
        image = Image.fromarray(cv2.cvtColor(image, cv2.COLOR_BGR2RGB)).convert('RGB')
    else:
        image = Image.fromarray(image).convert('L')
    return image

```

after you can restart the app
