### ISSUE TITLE
BiRefNet not installing in comfyUI after installing / restarting / etc. 

### ISSUE THREAD

**Issue by strouder** [ZHO-ZHO-ZHO/ComfyUI-BiRefNet-ZHO#30]
Everytime I load my workflow this pop up comes up in the beginning and trying to fix it in Install missing nodes... doesnt work.. I keep reinstalling it and even git https://github.com/ZHO-ZHO-ZHO/ComfyUI-BiRefNet-ZHO into the folder but it still doesnt work. 

![Screenshot 2024-10-30 201855](https://github.com/user-attachments/assets/ca769404-5df1-4ede-a936-d75c608375de)

![Screenshot 2024-10-30 201751](https://github.com/user-attachments/assets/0ca6f9a6-e429-4951-b6a7-cce8107b5375)

I get error in console

![Screenshot 2024-10-30 202002](https://github.com/user-attachments/assets/bad02060-e6db-4265-adc2-b110eb582b03)

```
Starting server

To see the GUI go to: http://127.0.0.1:8188
D:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
D:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
FETCH DATA from: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
D:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
D:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
D:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
[ERROR] An error occurred while retrieving information for the 'Florence2ModelLoader' node.
Traceback (most recent call last):
  File "D:\AI\ComfyUI\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 148, in INPUT_TYPES
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()], {"tooltip": "models are expected to be in Comfyui/models/LLM folder"}),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 148, in <listcomp>
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()], {"tooltip": "models are expected to be in Comfyui/models/LLM folder"}),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 931, in iterdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\AI\\ComfyUI\\ComfyUI\\models\\LLM'

D:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
D:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
[ERROR] An error occurred while retrieving information for the 'Florence2ModelLoader' node.
Traceback (most recent call last):
  File "D:\AI\ComfyUI\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 148, in INPUT_TYPES
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()], {"tooltip": "models are expected to be in Comfyui/models/LLM folder"}),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 148, in <listcomp>
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()], {"tooltip": "models are expected to be in Comfyui/models/LLM folder"}),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 931, in iterdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\AI\\ComfyUI\\ComfyUI\\models\\LLM'

data_path:  D:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\data
```

**Comment by Blackstylez83** [comment]
i have this experience too, is there any advice ?

**Comment by winnie-wildin** [comment]
same here, have tried installing it 2/3 times now

**Comment by fuzRodahh** [comment]
same here
